/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.0
 * Generated at: 2024-11-09 04:32:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class engg_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1731078913107L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"CSS/mystyle.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css\">\n");
      out.write("    <title>Engineering</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write(" ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\n");
      out.write("    <a class=\"navbar-brand\" href=\"#\" style=\"color: red\">UniNavigator</a>\n");
      out.write("  <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("    <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("  </button>\n");
      out.write("\n");
      out.write("  <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("    <ul class=\"navbar-nav mr-auto\">\n");
      out.write("      <li class=\"nav-item active\">\n");
      out.write("        <a class=\"nav-link\" href=\"index.jsp\">Home <i class=\"fas fa-house-user\"></i> <span class=\"sr-only\">(current)</span></a>\n");
      out.write("      </li>\n");
      out.write("      \n");
      out.write("      <li class=\"nav-item dropdown\">\n");
      out.write("        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("       Categories\n");
      out.write("        </a>\n");
      out.write("        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("          <a class=\"dropdown-item\" href=\"#\">Our Courses</a>\n");
      out.write("          <a class=\"dropdown-item\" href=\"#\">Universities List</a>\n");
      out.write("          <div class=\"dropdown-divider\"></div>\n");
      out.write("          <a class=\"dropdown-item\" href=\"#\">Contact Us</a>\n");
      out.write("        </div>\n");
      out.write("      </li>\n");
      out.write("      <li class=\"nav-item\">\n");
      out.write("        <a class=\"nav-link disabled\" href=\"#\">Disabled</a>\n");
      out.write("      </li>\n");
      out.write("    </ul>\n");
      out.write("    <form class=\"form-inline my-2 my-lg-0\">\n");
      out.write("      <input class=\"form-control mr-sm-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\n");
      out.write("      <button class=\"btn btn-outline-success my-2 my-sm-0\" type=\"submit\">Search</button>\n");
      out.write("    </form>\n");
      out.write("  </div>\n");
      out.write("</nav>");
      out.write("\n");
      out.write("    <section id=\"home\">\n");
      out.write("       \n");
      out.write("          \n");
      out.write("        <h1 class=\"h-primary\" style=\"font-size: 10vh; color: white;\" >B.Tech (Bachelor of Technology)</h1>\n");
      out.write("        <h3 class=\"heading\" style=\"font-size: 4vh;   color:brown; \" >Complete Course information, Admissions, Eligibility, Subjects, Syllabus, Cut-Off</h3>\n");
      out.write("        <h4 style=\"color: aliceblue;\"> “Engineering is the closest thing to magic that exists in the world.” </h4>\n");
      out.write("\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("        <p style=\"color: #000B58;\">B.Tech stands for Bachelor of Technology. It is an undergraduate degree focused on technical and engineering disciplines.\n");
      out.write("            B.Tech programs are highly popular in countries like India, as well as some parts of Europe and Asia. The degree\n");
      out.write("             is considered equivalent to the Bachelor of Engineering (BE) in most countries, although some institutions may differentiate \n");
      out.write("             between the two by focusing on a slightly more practical, application-oriented approach in B.Tech programs.</p>\n");
      out.write("\n");
      out.write("             <p style=\"color: black;font-size: 1rem;\"><b>1. Course Duration</b>\n");
      out.write("                 : A B.Tech program typically spans 4 years, divided into 8 semesters. Each semester includes core courses, lab sessions, project work, and practical training.\n");
      out.write("               <br><b> 2. Specializations</b>\n");
      out.write("                B.Tech offers various specializations, allowing students to focus on a specific engineering domain. Common branches include:\n");
      out.write("                \n");
      out.write("                Computer Science Engineering (CSE)\n");
      out.write("                Information Technology (IT)\n");
      out.write("                Mechanical Engineering\n");
      out.write("                Civil Engineering\n");
      out.write("                Electrical and Electronics Engineering (EEE)\n");
      out.write("                Electronics and Communication Engineering (ECE)\n");
      out.write("                Chemical Engineering\n");
      out.write("                Aerospace Engineering\n");
      out.write("                Biotechnology\n");
      out.write("                Environmental Engineering\n");
      out.write("                Automobile Engineering\n");
      out.write("                Agricultural Engineering, among others.\n");
      out.write("                <br><b>3. Eligibility Requirements</b>\n");
      out.write("                Education: Students must complete 10+2 (higher secondary education) with a focus on science subjects: Mathematics, Physics, and Chemistry.\n");
      out.write("                Entrance Exams: Admission often requires qualifying entrance exams, which can be:\n");
      out.write("                National-level: (e.g., JEE Main and JEE Advanced in India).\n");
      out.write("                State-level: (e.g., MHT CET in Maharashtra, WBJEE in West Bengal).\n");
      out.write("                University-specific: Some universities have their own exams (e.g., VITEEE for VIT, BITSAT for BITS Pilani).\n");
      out.write("               <br><b> 4. Course Structure and Curriculum</b>\n");
      out.write("                A typical B.Tech curriculum includes the following components:\n");
      out.write("                \n");
      out.write("                <br><b>Year 1: </b>Foundation Courses\n");
      out.write("                Mathematics (Calculus, Linear Algebra)\n");
      out.write("                Physics (Mechanics, Electricity, and Magnetism)\n");
      out.write("                Chemistry (for select branches)\n");
      out.write("                Basic Programming (often C, C++, or Python)\n");
      out.write("                Introduction to Engineering (overview of different branches and disciplines)\n");
      out.write("                Engineering Graphics and Workshop (technical drawing, tools, and machinery basics)\n");
      out.write("                <br><b>Year 2: </b>Core Engineering Courses\n");
      out.write("                Advanced Mathematics (Differential Equations, Statistics)\n");
      out.write("                Core subjects specific to chosen branch (e.g., Circuit Theory for EEE, Thermodynamics for Mechanical)\n");
      out.write("                Engineering Mechanics\n");
      out.write("                Data Structures and Algorithms (for CSE and IT)\n");
      out.write("                Materials Science\n");
      out.write("                Basic Electrical Engineering\n");
      out.write("                Lab Work (e.g., Physics and Chemistry Labs, Electronics Labs)\n");
      out.write("                <br><b>Year 3:</b> Specialized and Advanced Topics\n");
      out.write("                Branch-specific courses: This is where students start focusing on subjects specific to their field.\n");
      out.write("                Mechanical: Fluid Mechanics, Heat Transfer, Machine Design\n");
      out.write("                Civil: Structural Analysis, Hydraulics, Soil Mechanics\n");
      out.write("                CSE: Operating Systems, Database Management Systems, Computer Networks\n");
      out.write("                ECE: Digital Signal Processing, Microprocessors, and Embedded Systems\n");
      out.write("                Electives: Options to study topics like artificial intelligence, machine learning, renewable energy, robotics, etc.\n");
      out.write("                Industry-Oriented Labs and Simulations\n");
      out.write("                Mini Projects: Small-scale projects to apply learned concepts practically.\n");
      out.write("                <br><b>Year 4:</b> Advanced and Applied Learning\n");
      out.write("                Capstone Project / Final Year Project: A major project, often in collaboration with an industry partner, where students solve real-world problems in their field.\n");
      out.write("                Internships: Many programs require or encourage internships to gain hands-on experience.\n");
      out.write("                Elective Courses and Special Topics: Students can choose electives to further specialize in areas of interest.\n");
      out.write("                Technical Seminars and Workshops: Additional training on the latest industry trends and tools.\n");
      out.write("                <br><b>5. Types of Learning and Evaluation\n");
      out.write("                Lectures and Tutorials:</b> Classroom learning for theoretical concepts.\n");
      out.write("                Laboratories and Workshops: Hands-on experience with equipment, simulations, and software.\n");
      out.write("                Assignments and Projects: Continuous assessments through assignments, mini-projects, and lab reports.\n");
      out.write("                Examinations: Written exams at the end of each semester.\n");
      out.write("                Industrial Visits: Site visits to manufacturing plants, labs, and industries to observe engineering in real-world settings.\n");
      out.write("                <br><b>6. Skills Developed\n");
      out.write("                Technical Skills:</b> Proficiency in specific tools, techniques, and software relevant to the chosen branch.\n");
      out.write("                Problem-Solving Skills: Ability to apply engineering principles to solve complex technical issues.\n");
      out.write("                Analytical and Mathematical Skills: Understanding of quantitative methods and data analysis.\n");
      out.write("                Communication and Teamwork: Engineers often work in teams, so communication skills and teamwork are emphasized.\n");
      out.write("                Project Management: Skills in planning, executing, and managing engineering projects.\n");
      out.write("                <br><b>7. Career Opportunities After B.Tech\n");
      out.write("                Core Engineering Roles:</b> Design engineer, production engineer, R&D engineer, and quality assurance engineer.\n");
      out.write("                IT and Software Roles: For those with CSE and IT backgrounds, roles like software developer, data analyst, and systems engineer.\n");
      out.write("                Government Jobs: Many B.Tech graduates work in public sector jobs (like Indian Engineering Services in India).\n");
      out.write("                Consulting and Management: Engineers often transition into consulting or management roles after gaining experience.\n");
      out.write("                Higher Studies: Graduates can pursue further education like:\n");
      out.write("                M.Tech (Master of Technology) for deeper specialization.\n");
      out.write("                MS (Master of Science) abroad, especially for research-oriented roles.\n");
      out.write("                MBA (Master of Business Administration) for management positions.\n");
      out.write("                <br><b>8. Higher Studies and Certifications</b>\n");
      out.write("                After B.Tech, students can enhance their qualifications with:\n");
      out.write("                M.Tech or ME (Master of Engineering): Specialize further in a chosen field.\n");
      out.write("                Ph.D.: For those interested in research or academia.\n");
      out.write("                Certifications: Courses in programming, data science, machine learning, project management, etc., are popular choices.\n");
      out.write("                <br><b>9. Comparison with BE (Bachelor of Engineering)\n");
      out.write("                B.Tech:</b> Often emphasizes application-oriented and practical skills.\n");
      out.write("                BE: Tends to focus more on the theoretical foundations of engineering, though this varies by country and institution.\n");
      out.write("                <br><b>10. Example Semester-Wise Course Outline (Computer Science & Engineering)</b>\n");
      out.write("                <b>Semester 1-2:</b> Mathematics, Physics, Basic Programming, Engineering Graphics\n");
      out.write("                <b>Semester 3-4:</b> Data Structures, Algorithms, Digital Electronics, Operating Systems\n");
      out.write("                <b>Semester 5-6:</b> Computer Networks, Database Management, Microprocessors, Machine Learning (elective)\n");
      out.write("                <b>Semester 7-8:</b> Project Management, Capstone Project, Electives (AI, Data Science, Cloud Computing)\n");
      out.write("                <br><b>\n");
      out.write("                A B.Tech degree equips students with essential engineering and technical skills required for various industries.\n");
      out.write("                 The blend of theoretical knowledge, practical experience, and industry exposure ensures \n");
      out.write("                graduates are well-prepared for engineering careers, research roles, and entrepreneurial ventures.</b>\n");
      out.write("                \n");
      out.write("                \n");
      out.write("                \n");
      out.write("                \n");
      out.write("                \n");
      out.write("                \n");
      out.write("                </p>\n");
      out.write("    \n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
