/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.0
 * Generated at: 2024-11-09 05:49:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.ebook.helper.ConnectionProvider;
import java.sql.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1731131341143L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.ebook.helper.ConnectionProvider");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"CSS/mystyle.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css\">\n");
      out.write("        <title>J SP Page</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\n");
      out.write("    <a class=\"navbar-brand\" href=\"#\" style=\"color: red\">UniNavigator</a>\n");
      out.write("  <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("    <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("  </button>\n");
      out.write("\n");
      out.write("  <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("    <ul class=\"navbar-nav mr-auto\">\n");
      out.write("      <li class=\"nav-item active\">\n");
      out.write("        <a class=\"nav-link\" href=\"index.jsp\">Home <i class=\"fas fa-house-user\"></i> <span class=\"sr-only\">(current)</span></a>\n");
      out.write("      </li>\n");
      out.write("      <li class=\"nav-item active\">\n");
      out.write("        <a class=\"nav-link\" href=\"Login.jsp\">Login <i class=\"fas fa-user\"></i> <span class=\"sr-only\">(current)</span></a>\n");
      out.write("      </li>\n");
      out.write("      <li class=\"nav-item dropdown\">\n");
      out.write("        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("       Categories\n");
      out.write("        </a>\n");
      out.write("        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("          <a class=\"dropdown-item\" href=\"#\">Our Courses</a>\n");
      out.write("          <a class=\"dropdown-item\" href=\"#\">Universities List</a>\n");
      out.write("          <div class=\"dropdown-divider\"></div>\n");
      out.write("          <a class=\"dropdown-item\" href=\"#\">Contact Us</a>\n");
      out.write("        </div>\n");
      out.write("      </li>\n");
      out.write("      <li class=\"nav-item\">\n");
      out.write("        <a class=\"nav-link disabled\" href=\"#\">Disabled</a>\n");
      out.write("      </li>\n");
      out.write("    </ul>\n");
      out.write("    <form class=\"form-inline my-2 my-lg-0\">\n");
      out.write("      <input class=\"form-control mr-sm-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\n");
      out.write("      <button class=\"btn btn-outline-success my-2 my-sm-0\" type=\"submit\">Search</button>\n");
      out.write("    </form>\n");
      out.write("  </div>\n");
      out.write("</nav>");
      out.write(" \n");
      out.write("\n");
      out.write("        <section class=\"header\" style=\"background-image: url(Images/kapo.avif;)\">\n");
      out.write("\n");
      out.write("            <div class=\"text-box\">\n");
      out.write("                <h1 style=\"color: #D2E0FB\">Find Your Perfect University Match</h1>\n");
      out.write("                <p style=\"color: white; font-size: 24px\">Welcome to UniNavigator, your comprehensive guide to discovering, comparing, \n");
      out.write("                    and choosing the perfect university for your future.</p>\n");
      out.write("                <a href=\"register.jsp\" class=\"hero-btn\"style=\"background: black\">Visit Us To Know More</a>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        \n");
      out.write("        <section id=\"slider\">\n");
      out.write("            <h2 style=\"margin-left: 38%;font-size: 3rem;color: red\"> Courses we  offer <h2>\n");
      out.write("                     \n");
      out.write("                    <div class=\"container\">\n");
      out.write("                        <input type=\"radio\" name=\"dot\" id=\"one\">\n");
      out.write("                        <input type=\"radio\" name=\"dot\" id=\"two\">\n");
      out.write("                        <div class=\"main-card\">\n");
      out.write("                            <div class=\"cards\">\n");
      out.write("                                <div class=\"card\"style=\"color: grey\">\n");
      out.write("                                    <div class=\"content\">\n");
      out.write("\n");
      out.write("                                        <div class=\"details\">\n");
      out.write("                                            <div class=\"name\">Engineering</div>\n");
      out.write("                                            <div class=\"job\"> It’s a field that combines creativity and technical knowledge to solve real-world problems, \n");
      out.write("                                                often making things work more efficiently, safely, and sustainably.</div>\n");
      out.write("                                            <a class=\"btn\" href=\"engg.jsp\" style=\"color:white; margin-top: 10%; background-color: #091057;\" >Know More</a>\n");
      out.write("                                        </div>\n");
      out.write("\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"card\" style=\"margin-left: 1%; color: gray\">\n");
      out.write("                                    <div class=\"content\">\n");
      out.write("                                        <div class=\"details\">\n");
      out.write("                                            <div class=\"name\">Pharmacy</div>\n");
      out.write("                                            <div class=\"job\">Pharmacists are healthcare professionals trained in the science of medications, \n");
      out.write("                                                including their effects, uses, and potential side effects.</div>\n");
      out.write("                                            <a class=\"btn\" href=\"pharma.jsp\" style=\"color:white; margin-top: 10%; background-color: #091057;\" >Know More</a>\n");
      out.write("                                        </div>\n");
      out.write("\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"card\" style=\"margin-left: 1%;\">\n");
      out.write("                                    <div class=\"content\">\n");
      out.write("                                        <div class=\"details\">\n");
      out.write("                                            <div class=\"name\">MBA</div>\n");
      out.write("                                            <div class=\"job\">Bachelor of Computer Applications (BCA) is an undergraduate degree program in the field of computer science and applications.</div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <a class=\"btn\" href=\"mba.jsp\" style=\"color:white; margin-top: 10%; background-color: #091057;\" >Know More</a>\n");
      out.write("\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"card\" style=\"margin-left: 1%;\">\n");
      out.write("                                    <div class=\"content\">\n");
      out.write("                                        <div class=\"details\">\n");
      out.write("                                            <div class=\"name\">BCA</div>\n");
      out.write("                                            <div class=\"job\">It is designed to provide students with the essential skills and knowledge required for a career in software development, IT services, and computer science in general. </div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <a class=\"btn\" style=\"color:white; margin-top: 10%; background-color: #091057;\" >Know More</a>\n");
      out.write("\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"card\" style=\"margin-left: 1%;\">\n");
      out.write("                                    <div class=\"content\">\n");
      out.write("                                        <div class=\"details\">\n");
      out.write("                                            <div class=\"name\">Diploma</div>\n");
      out.write("                                            <div class=\"job\">Diplomas are offered in various fields, including engineering, business, healthcare, education, design, arts, technology, and more.</div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <a class=\"btn\" style=\"color:white; margin-top: 10%; background-color: #091057;\" >Know More</a>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("                                <div class=\"card\" style=\"margin-left: 1%;\">\n");
      out.write("                                    <div class=\"content\">\n");
      out.write("                                        <div class=\"details\">\n");
      out.write("                                            <div class=\"name\">BSC</div>\n");
      out.write("                                            <div class=\"job\">Bachelor of Science (BSc) is an undergraduate academic degree awarded in the field of science.</div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <a class=\"btn\" style=\"color:white; margin-top: 10%; background-color: #091057;\" >Know More</a>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                   \n");
      out.write("                        <div class=\"button\">\n");
      out.write("                            <label for=\"one\" class=\"one active\"></label>\n");
      out.write("                            <label for=\"two\" class=\"two\"></label>\n");
      out.write("                        </div>\n");
      out.write("                     \n");
      out.write("                    </div>\n");
      out.write("                    </section>\n");
      out.write("\n");
      out.write("                    <!-- ---------------------campus------------------ -->\n");
      out.write("                    <section class=\"campus\">\n");
      out.write("                        <h1  style=\" color:#091057;\n");
      out.write("                             font-family: Arial, Helvetica, sans-serif; margin-left: 1%;\">University List</h1> \n");
      out.write("\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                            <div class=\"campus-col\">\n");
      out.write("                                <img src=\"Images/uiit.jpeg\">\n");
      out.write("                                <div class=\"layer\">\n");
      out.write("                                    <h3>IIT</h3>\n");
      out.write("                                    <a href=\"https://home.iitd.ac.in/\" class=\"btn\"  >Visit</a>\n");
      out.write("                                     <a href=\"college.jsp\" class=\"btn\" >Explore</a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"campus-col\">\n");
      out.write("                                <img src=\"Images/unit.jpeg\">\n");
      out.write("                                <div class=\"layer\">\n");
      out.write("                                    <h3>NIT</h3>\n");
      out.write("                                    <a href=\"https://nitdelhi.ac.in/\" class=\"btn\">Visit</a>\n");
      out.write("                                    <a href=\"coll1.jsp\" class=\"btn\" >Explore</a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"campus-col\">\n");
      out.write("                                <img src=\"Images/udyp.jpg\">\n");
      out.write("                                <div class=\"layer\">\n");
      out.write("                                    <h3>D.Y.Patil</h3>\n");
      out.write("                                    <a href=\"https://dypatil.edu/\" class=\"btn\" >Visit</a>\n");
      out.write("                                     <a href=\"college.jsp\" class=\"btn\" >Explore</a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                            <div class=\"campus-col\">\n");
      out.write("                                <img src=\"Images/udb.jpeg\">\n");
      out.write("                                <div class=\"layer\">\n");
      out.write("                                    <h3>DBATU</h3>\n");
      out.write("                                    <a href=\"https://dbatu.ac.in/\" class=\"btn\" style=\"margin-top: 55%;\" >Visit</a>\n");
      out.write("                                  <a href=\"college.jsp\" class=\"btn\" >Explore</a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"campus-col\">\n");
      out.write("                                <img src=\"Images/upn.jpeg\">\n");
      out.write("                                <div class=\"layer\">\n");
      out.write("                                    <h3>Savitribai Phule</h3>\n");
      out.write("                                    <a href=\"http://www.unipune.ac.in/\" class=\"btn\" style=\"margin-top: 55%;\" >Visit</a>\n");
      out.write("                                <a href=\"college.jsp\" class=\"btn\" >Explore</a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"campus-col\">\n");
      out.write("                                <img src=\"Images/unmu.jpg\">\n");
      out.write("                                <div class=\"layer\">\n");
      out.write("                                    <h3>NMU</h3>\n");
      out.write("                                    <a href=\"https://nmu.ac.in/en-us/\" class=\"btn\" style=\"margin-top: 55%;\" >Visit</a>\n");
      out.write("                                     <a href=\"college.jsp\" class=\"btn\" >Explore</a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </section>\n");
      out.write("\n");
      out.write("                    <section class=\"contact\">\n");
      out.write("                        <div class=\"contact-text\">\n");
      out.write("                            <h2 style=\"color: blue\">Contact Us</h2>\n");
      out.write("                            <!--                <h4>Let's Work Together</h4>-->\n");
      out.write("                            <p>At University Guider, we’re here to support you on your educational journey. Whether you have questions about specific universities, need guidance with applications, or seek advice on choosing the right course, our team is ready to help. Don’t hesitate to reach out! Connect with us via email, phone, or our online contact form, and we’ll respond as soon as possible. We look forward to assisting you in making informed and confident decisions for your future.\n");
      out.write("                                </p>\n");
      out.write("                            <div class=\"contact-list\">\n");
      out.write("                                <li><a href=\"#\"><i class='bx bx-send bx-tada' ></i></a>contact@gmail.com</li>\n");
      out.write("                                <li><a href=\"#\"><i class='bx bx-phone bx-tada' ></i></a>1234567890</li>\n");
      out.write("                            </div>\n");
      out.write("                            \n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"contact-form\">\n");
      out.write("                            <form action=\"\">\n");
      out.write("                                <input type=\"\" placeholder=\"Enter Your Name\" required>\n");
      out.write("                                <input type=\"email\" placeholder=\"Enter Your Email\" required>\n");
      out.write("\n");
      out.write("                                <input type=\"\" placeholder=\"Enter Your Subject\">\n");
      out.write("                                <textarea name=\"\" id=\"\" cols=\"40\" rows=\"10\" placeholder=\"Enter Your message\" required></textarea>\n");
      out.write("                                <input type=\"submit\" value=\"submit\" class=\"send\">\n");
      out.write("                            </form>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                    </section> \n");
      out.write("\n");
      out.write("\n");
      out.write("                    <footer class=\"footer\">\n");
      out.write("                        <div class=\"footer-container\">\n");
      out.write("                            <div class=\"footer-section\">\n");
      out.write("                                <h4>About Us</h4>\n");
      out.write("                                <p>Learn more about our company and our mission to provide the best service.</p>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <div class=\"footer-section\">\n");
      out.write("                                <h4>Quick Links</h4>\n");
      out.write("                                <ul>\n");
      out.write("                                    <li><a href=\"#\">Home</a></li>\n");
      out.write("                                    <li><a href=\"#\">Services</a></li>\n");
      out.write("                                    <li><a href=\"#\">Contact</a></li>\n");
      out.write("                                    <li><a href=\"#\">Blog</a></li>\n");
      out.write("                                </ul>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <div class=\"footer-section\">\n");
      out.write("                                <h4>Follow Us</h4>\n");
      out.write("                                <div class=\"social-icons\">\n");
      out.write("                                    <a href=\"#\"><i class=\"fab fa-facebook-f\"></i></a>\n");
      out.write("                                    <a href=\"#\"><i class=\"fab fa-twitter\"></i></a>\n");
      out.write("                                    <a href=\"#\"><i class=\"fab fa-instagram\"></i></a>\n");
      out.write("                                    <a href=\"#\"><i class=\"fab fa-linkedin\"></i></a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"footer-bottom\">\n");
      out.write("                            <p>&copy; 2024 YourCompany. All Rights Reserved.</p>\n");
      out.write("                        </div>\n");
      out.write("                    </footer>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <!--    <h1>Hello World!</h1>\n");
      out.write("                    ");

                        Connection con = ConnectionProvider.getConnection();

                    
      out.write("\n");
      out.write("                    <h1>");
      out.print(con);
      out.write("</h1>-->\n");
      out.write("                    <script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\" crossorigin=\"anonymous\"></script>\n");
      out.write("                    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js\" integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\" crossorigin=\"anonymous\"></script>\n");
      out.write("                    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js\" integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\" crossorigin=\"anonymous\"></script>\n");
      out.write("                    </body>\n");
      out.write("                    </html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
