/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.0
 * Generated at: 2024-11-09 05:41:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class mba_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1731078913107L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"CSS/mystyle.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css\">\n");
      out.write("        <title>Engineering</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("       ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\n");
      out.write("    <a class=\"navbar-brand\" href=\"#\" style=\"color: red\">UniNavigator</a>\n");
      out.write("  <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("    <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("  </button>\n");
      out.write("\n");
      out.write("  <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("    <ul class=\"navbar-nav mr-auto\">\n");
      out.write("      <li class=\"nav-item active\">\n");
      out.write("        <a class=\"nav-link\" href=\"index.jsp\">Home <i class=\"fas fa-house-user\"></i> <span class=\"sr-only\">(current)</span></a>\n");
      out.write("      </li>\n");
      out.write("      \n");
      out.write("      <li class=\"nav-item dropdown\">\n");
      out.write("        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("       Categories\n");
      out.write("        </a>\n");
      out.write("        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("          <a class=\"dropdown-item\" href=\"#\">Our Courses</a>\n");
      out.write("          <a class=\"dropdown-item\" href=\"#\">Universities List</a>\n");
      out.write("          <div class=\"dropdown-divider\"></div>\n");
      out.write("          <a class=\"dropdown-item\" href=\"#\">Contact Us</a>\n");
      out.write("        </div>\n");
      out.write("      </li>\n");
      out.write("      <li class=\"nav-item\">\n");
      out.write("        <a class=\"nav-link disabled\" href=\"#\">Disabled</a>\n");
      out.write("      </li>\n");
      out.write("    </ul>\n");
      out.write("    <form class=\"form-inline my-2 my-lg-0\">\n");
      out.write("      <input class=\"form-control mr-sm-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\n");
      out.write("      <button class=\"btn btn-outline-success my-2 my-sm-0\" type=\"submit\">Search</button>\n");
      out.write("    </form>\n");
      out.write("  </div>\n");
      out.write("</nav>");
      out.write("\n");
      out.write("        <section id=\"home\">\n");
      out.write("\n");
      out.write("\n");
      out.write("            <h1 class=\"h-primary\" style=\"font-size: 10vh; color: white;\" >Master of Business Administration(MBA)</h1>\n");
      out.write("            <h3 class=\"heading\" style=\"font-size: 4vh;   color:brown; \" >Complete Course information, Admissions, Eligibility, Subjects, Syllabus, Cut-Off</h3>\n");
      out.write("            <h4 style=\"color: aliceblue;\"> “It does not matter how slowly you go as long as you do not stop.”  </h4>\n");
      out.write("\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <p style=\"color: #000B58;\"> is a graduate-level degree focused on building skills in business management, strategy, finance, marketing, and leadership.\n");
      out.write("            An MBA program generally provides a comprehensive curriculum covering foundational and advanced topics in business.\n");
      out.write("            <br> Here’s an overview of common courses and learning areas:-</p>\n");
      out.write("\n");
      out.write("        <p style=\"color: black;font-size: 1rem;\"><b>1. Core Courses</b>\n");
      out.write("            Core courses are designed to provide a strong foundation in essential business principles.\n");
      out.write("\n");
      out.write("            <br><b>Financial Accounting:</b> Understanding financial statements, accounting principles, and how to analyze financial health.\n");
      out.write("            <br><b>Managerial Economics:</b> Applying economic principles to decision-making and understanding market forces.\n");
      out.write("            <br><b>Corporate Finance:</b> Focus on capital structure, budgeting, valuation, and financial strategies.\n");
      out.write("            <br><b>Marketing Management:</b> Exploring consumer behavior, market segmentation, branding, and strategic marketing.\n");
      out.write("            <br><b>Operations Management:</b> Studying production, supply chain logistics, quality control, and process optimization.\n");
      out.write("            <br><b>Organizational Behavior: </b> team dynamics, leadership, and corporate culture.\n");
      out.write("            <br><b>Strategic Management:</b> Analyzing competitive advantage, business models, and long-term strategic planning.\n");
      out.write("\n");
      out.write("            <br><b> 2. Specialization Courses</b>\n");
      out.write("            Most MBA programs allow students to specialize in areas based on their interests and career goals.\n");
      out.write("\n");
      out.write("            <br><b>Finance:</b> Advanced corporate finance, investment analysis, portfolio management, financial derivatives.\n");
      out.write("            <br><b>Marketing:</b> Digital marketing, brand strategy, marketing analytics, and consumer insights.\n");
      out.write("            <br><b>Entrepreneurship:</b> Venture creation, innovation management, business planning, and new product development.\n");
      out.write("            <br><b>Consulting:</b> Problem-solving frameworks, industry analysis, strategic consulting techniques.\n");
      out.write("            <br><b>Supply Chain Management: </b>Logistics, procurement, supply chain analytics, and inventory management.\n");
      out.write("            <br><b>Human Resources: </b>Talent management, organizational development, diversity and inclusion, and labor law.\n");
      out.write("\n");
      out.write("            <br><b>3. Electives</b>\n");
      out.write("            Electives allow students to explore topics outside of core requirements or their specialization.\n");
      out.write("\n");
      out.write("            Examples include:\n");
      out.write("\n");
      out.write("            <br><b>International Business: </b>Managing multinational corporations, global market entry, and cross-cultural management.\n");
      out.write("            <br><b>Data Analytics: </b>Big data, business intelligence, predictive analytics, and decision modeling.\n");
      out.write("            <br><b>Technology Management:</b> Innovation in tech-driven industries, product management, and digital transformation.\n");
      out.write("            <br><b>Corporate Social Responsibility (CSR):</b> Ethical business practices, sustainability, and social impact.\n");
      out.write("\n");
      out.write("            <br><b>4. Capstone Projects and Internships</b>\n");
      out.write("            <br><b>Capstone Project:</b> A real-world project that allows students to apply their learning in a strategic business challenge.\n");
      out.write("            <br><b>Internships:</b> Many full-time MBA programs offer internship opportunities, providing hands-on experience in specific industries.\n");
      out.write("\n");
      out.write("            <br><b>5. Leadership and Soft Skills</b>\n");
      out.write("            Programs often include courses and workshops on negotiation, public speaking, teamwork, and conflict resolution. Leadership courses help\n");
      out.write("            students build self-awareness, emotional intelligence, \n");
      out.write("            and interpersonal skills essential for managing teams and driving organizational success.\n");
      out.write("\n");
      out.write("\n");
      out.write("            <br><b>6. Global and Ethical Perspectives</b> \n");
      out.write("            <br><b>Global Immersion:</b> Many MBA programs offer international trips or modules to expose students to business practices in different cultures.\n");
      out.write("            <br><b>Business Ethics: </b>Exploring ethical challenges in decision-making, corporate governance, and social responsibility.\n");
      out.write("\n");
      out.write("            <br><b>Typical MBA Formats</b>\n");
      out.write("            <br><b>Full-time MBA:</b> Typically 1-2 years, immersive with a cohort model.\n");
      out.write("            <br><b>Part-time MBA:</b> Takes 3-4 years, flexible for working professionals.\n");
      out.write("            <br><b>Executive MBA (EMBA):</b> Designed for senior executives, with a focus on strategic leadership and management.\n");
      out.write("            <br><b>Online MBA:</b> Fully online, offering flexibility for remote learning.\n");
      out.write("            <br><b>An MBA is a highly customizable experience, allowing students to tailor their education to suit their career ambitions and industry interests.\n");
      out.write("\n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
