/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.0
 * Generated at: 2024-11-09 05:42:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class pharma_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1731078913107L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"CSS/mystyle.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css\">\n");
      out.write("        <title>Engineering</title>\n");
      out.write("        \n");
      out.write("        \n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        \n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\n");
      out.write("    <a class=\"navbar-brand\" href=\"#\" style=\"color: red\">UniNavigator</a>\n");
      out.write("  <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("    <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("  </button>\n");
      out.write("\n");
      out.write("  <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("    <ul class=\"navbar-nav mr-auto\">\n");
      out.write("      <li class=\"nav-item active\">\n");
      out.write("        <a class=\"nav-link\" href=\"index.jsp\">Home <i class=\"fas fa-house-user\"></i> <span class=\"sr-only\">(current)</span></a>\n");
      out.write("      </li>\n");
      out.write("      \n");
      out.write("      <li class=\"nav-item dropdown\">\n");
      out.write("        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("       Categories\n");
      out.write("        </a>\n");
      out.write("        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("          <a class=\"dropdown-item\" href=\"#\">Our Courses</a>\n");
      out.write("          <a class=\"dropdown-item\" href=\"#\">Universities List</a>\n");
      out.write("          <div class=\"dropdown-divider\"></div>\n");
      out.write("          <a class=\"dropdown-item\" href=\"#\">Contact Us</a>\n");
      out.write("        </div>\n");
      out.write("      </li>\n");
      out.write("      <li class=\"nav-item\">\n");
      out.write("        <a class=\"nav-link disabled\" href=\"#\">Disabled</a>\n");
      out.write("      </li>\n");
      out.write("    </ul>\n");
      out.write("    <form class=\"form-inline my-2 my-lg-0\">\n");
      out.write("      <input class=\"form-control mr-sm-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\n");
      out.write("      <button class=\"btn btn-outline-success my-2 my-sm-0\" type=\"submit\">Search</button>\n");
      out.write("    </form>\n");
      out.write("  </div>\n");
      out.write("</nav>");
      out.write("\n");
      out.write("        <section id=\"home\">\n");
      out.write("\n");
      out.write("\n");
      out.write("            <h1 class=\"h-primary\" style=\"font-size: 10vh; color: white;\" >Bachelor of Pharmacy (B.Pharm)</h1>\n");
      out.write("            <h3 class=\"heading\" style=\"font-size: 4vh;   color:brown; \" >Complete Course information, Admissions, Eligibility, Subjects, Syllabus, Cut-Off</h3>\n");
      out.write("            <h4 style=\"color: aliceblue;\"> \"It is easy to get a thousand prescriptions, but hard to get one single remedy\"  </h4>\n");
      out.write("\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <p style=\"color: #000B58;\">A Bachelor of Pharmacy (B.Pharm) degree is an undergraduate program designed to prepare \n");
      out.write("            students for careers in the pharmaceutical and healthcare industries. The course provides a strong foundation in medical \n");
      out.write("            science, drug therapy, pharmaceutical chemistry, and pharmacology, \n");
      out.write("            aiming to equip students with the skills needed to develop, test, manufacture, and market drugs.</p>\n");
      out.write("\n");
      out.write("        <p style=\"color: black;font-size: 1rem;\"><b>1. Course Duration</b>\n");
      out.write("            The B.Pharm program is generally a 4-year course divided into 8 semesters.\n");
      out.write("            Some countries also offer Pharm.D. (Doctor of Pharmacy) programs, which can extend up to 6 years, focusing more on clinical practice.\n");
      out.write("\n");
      out.write("            <br><b> 2. Eligibility Requirements</b>\n");
      out.write("            Educational Qualification: Students must complete 10+2 (high school) with science subjects—specifically Biology, Physics, and Chemistry. In some cases, Mathematics may also be accepted.\n");
      out.write("            Minimum Marks: Requirements vary, but students typically need a minimum of 50% in their qualifying exams.\n");
      out.write("            Entrance Exams: Admission to pharmacy programs can depend on entrance exams, especially in countries like India (e.g., GPAT or state-level exams), or may be merit-based in other places.\n");
      out.write("\n");
      out.write("            <br><b>3. Types of Pharmacy Degrees</b>\n");
      out.write("            B.Pharm (Bachelor of Pharmacy): A 4-year program focused on all aspects of pharmacy.\n");
      out.write("            Pharm.D (Doctor of Pharmacy): A 6-year program with an emphasis on clinical pharmacy, patient care, and therapeutic practice.\n");
      out.write("            D.Pharm (Diploma in Pharmacy): A 2-year diploma program often considered a stepping stone to B.Pharm for those wanting a shorter program.\n");
      out.write("\n");
      out.write("            <br><b> 4. Core Subjects and Curriculum</b>\n");
      out.write("            Pharmacy education combines theoretical knowledge, laboratory skills, and clinical training. The curriculum typically includes:\n");
      out.write("\n");
      out.write("            <br><b>Year 1: Basic Sciences and Fundamentals </b>Pharmaceutical Chemistry: Basic concepts in organic, inorganic, and physical chemistry.\n");
      out.write("            Human Anatomy and Physiology: Understanding human body systems, structure, and function.\n");
      out.write("            Biochemistry: Study of biochemical processes and their relevance in drug action.\n");
      out.write("            Pharmaceutics: Introduction to drug formulation, types of dosage forms, and drug delivery systems.\n");
      out.write("            Mathematics and Computer Applications: Basics of calculations and IT skills relevant to pharmacy.\n");
      out.write("\n");
      out.write("            <br><b>Year 2: Pharmaceutical Sciences </b>Pharmacognosy: Study of natural drugs from plants and animals.\n");
      out.write("            Pharmaceutical Microbiology: Microorganisms, their effects, and the role of microbiology in drug production.\n");
      out.write("            Pathophysiology: Understanding disease mechanisms and symptoms.\n");
      out.write("            Physical Pharmacy: Focus on the physical and chemical properties of drugs.\n");
      out.write("            Pharmaceutical Jurisprudence: Overview of pharmacy laws, regulations, and ethics.\n");
      out.write("\n");
      out.write("            <br><b>Year 3: Advanced Pharmacy Concepts</b> Pharmacology: Study of drug effects, mechanisms of action, therapeutic uses, and side effects.\n");
      out.write("            Medicinal Chemistry: Synthesis, analysis, and chemical properties of medicinal compounds.\n");
      out.write("            Pharmaceutical Analysis: Techniques for drug analysis, quality control, and standardization.\n");
      out.write("            Pharmaceutics II: Advanced study of formulation and manufacturing techniques for various dosage forms.\n");
      out.write("\n");
      out.write("            <br><b>Year 4: Clinical and Industrial Pharmacy</b> Pharmacotherapeutics: Principles of drug therapy and patient-centered treatment.\n");
      out.write("            Hospital and Clinical Pharmacy: Practical knowledge of pharmacy in a clinical setting, including patient care.\n");
      out.write("            Pharmaceutical Biotechnology: Biotechnology applications in drug production, including vaccines, enzymes, and bio-drugs.\n");
      out.write("            Research Project: In the final year, students often undertake a project that involves research and practical application of what they have learned.\n");
      out.write("\n");
      out.write("            <br><b>5. Laboratory and Practical Training\n");
      out.write("                Labs:</b> Pharmacy education includes a lot of laboratory work, allowing students to gain hands-on experience in pharmaceutical manufacturing, compounding, and analysis.\n");
      out.write("            Practical Skills: Practical training covers areas like drug formulation, dispensing, and quality control.\n");
      out.write("            Internships: Many programs require students to complete internships in hospitals or pharmaceutical companies to gain real-world experience.\n");
      out.write("\n");
      out.write("            <br><b>Written Exams:</b>  Held at the end of each semester, covering theory-based knowledge.\n");
      out.write("            <b>Practical Exams: </b>Testing skills in laboratory and clinical settings.\n");
      out.write("            <b>Assignments and Presentations: </b>Often given to assess knowledge and communication skills.\n");
      out.write("            <b>Projects and Research Work:</b> Practical projects involving research, often in the final year.\n");
      out.write("\n");
      out.write("            <br><b>7. Career Opportunities</b> \n");
      out.write("            After completing a pharmacy degree, graduates have diverse career paths in fields like healthcare, industry, government, and research. Common roles include:\n");
      out.write("\n");
      out.write("            Pharmacist: Dispensing medications and providing counseling in pharmacies and hospitals.\n");
      out.write("            Clinical Pharmacist: Working in healthcare settings to provide therapeutic drug monitoring and patient care.\n");
      out.write("            Pharmaceutical Scientist: Engaging in research and development of new drugs and therapies.\n");
      out.write("            Quality Control/Quality Assurance: Ensuring the safety and efficacy of drugs in manufacturing.\n");
      out.write("            Regulatory Affairs Specialist: Managing compliance with pharmaceutical regulations and guidelines.\n");
      out.write("            Sales and Marketing: Working with pharmaceutical companies to promote and sell new drugs.\n");
      out.write("            Academics and Research: Teaching or conducting research at universities and institutes.\n");
      out.write("            Drug Inspector: Monitoring the quality and distribution of pharmaceuticals, often a government role.\n");
      out.write("\n");
      out.write("            <br><b>8. Higher Studies and Certifications</b>\n");
      out.write("            Master’s in Pharmacy (M.Pharm): Advanced specialization in areas like pharmacology, pharmaceutics, pharmacognosy, etc.\n");
      out.write("            Pharm.D (Doctor of Pharmacy): For those seeking advanced clinical roles, especially popular in the U.S. and some other countries.\n");
      out.write("            MBA in Pharmaceutical Management: For those interested in the business side of pharmacy and healthcare.\n");
      out.write("            Ph.D. in Pharmaceutical Sciences: For research and academic careers, focused on deep scientific study.\n");
      out.write("            Specialized Certifications: Certifications in areas like clinical research, regulatory affairs, pharmacovigilance, and quality assurance.\n");
      out.write("\n");
      out.write("            <br><b>9. Pharmacy Licensing and Professional Exams:</b> In most countries, pharmacists must pass a licensing exam to practice. Examples include:\n");
      out.write("            NAPLEX (North American Pharmacist Licensure Examination) in the U.S.\n");
      out.write("            GPhC Registration Assessment in the U.K.\n");
      out.write("            PCI Registration in India.\n");
      out.write("            Continuing education and certifications are often required to maintain licensure.\n");
      out.write("\n");
      out.write("            <br><b>10.Example Semester-Wise Course Outline (B.Pharm)</b>\n");
      out.write("            <b>Semester 1-2:</b>  Basic subjects like Pharmaceutical Chemistry, Anatomy, Physiology, and Biochemistry.\n");
      out.write("            <b>Semester 3-4:</b>Core pharmaceutical sciences like Pharmacology, Pharmaceutical Microbiology, and Pathophysiology.\n");
      out.write("            <b>Semester 5-6:</b> Advanced topics in Medicinal Chemistry, Pharmaceutical Analysis, and Pharmaceutics.\n");
      out.write("            <b>Semester 7-8:</b> Clinical Pharmacy, Pharmaceutical Biotechnology, and research projects.\n");
      out.write("            <br><b>\n");
      out.write("                Pharmacy is a dynamic and evolving field, merging healthcare and science. A degree in pharmacy not only offers job stability but also the chance to contribute to public health by ensuring the safe and effective use of medications. Graduates have diverse career options, ranging from patient care to industry roles, making it a rewarding and versatile profession.</b>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        </p>\n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
